package es.inmobiliaria.hibernate;
// Generated 31-ene-2015 22:06:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private Integer id;
     private String titulo;
     private BigDecimal precio;
     private String direccion;
     private String usuario;

    public Inmueble() {
    }

    public Inmueble(String titulo, BigDecimal precio, String direccion, String usuario) {
       this.titulo = titulo;
       this.precio = precio;
       this.direccion = direccion;
       this.usuario = usuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }




}


